version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: medicore-frontend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
